apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  generation: 1
  labels:
    run: app
  name: app
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      run: app
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: app
    spec:
      containers:
      - command:
        - rails
        - s
        - -p
        - "3000"
        - -b
        - 0.0.0.0
        image: 546124439885.dkr.ecr.us-east-1.amazonaws.com/guest_book:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: PGHOST
          value: "db"
        - name: PGDB
          value: "GuestBook_development"
        - name: PGUSER
          value: "docker"
        - name: PGPASS
          value: "example"
        name: app
        ports:
        - containerPort: 3000
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
